#!/usr/bin/env bash

if [ -n "$(git status --porcelain)" ]; then
    echo "🧹 clean up first"
    exit 1
fi

branch_name=$(git symbolic-ref -q HEAD)
branch_name=${branch_name##refs/heads/}
branch_name=${branch_name:-HEAD}

if [[ "$branch_name" == *"main" ]]; then
    echo "❌ you are on the main branch"
    exit 1
else
    echo "✅ creating pr for $branch_name"
fi

title=${1:-$(git log -1 --format=%s)}
body=""

shift

echo ""
commits=$(git rev-list origin/main..HEAD)
num_commits=$(echo "$commits" | wc -l)

for sha in $commits; do
    commit_title=$(git show -s --format=%s "$sha")
    content=$(git log -1 --format=%b "$sha")
    if [ "$num_commits" -gt 1 ]; then
        body+="* $commit_title"$'\n'
        if [ -n "$content" ]; then
            body+="  "
        fi
    fi
    if [ -n "$content" ]; then
        body+="$content"$'\n'
    fi
done
printf "📋 %s\n\n%s" "$title" "$body"
echo ""
read -p "🤔 is this ok? [y/n] " -n 1 -r
if ! git push --set-upstream origin "$branch_name"; then
    echo "❌ failed to push"
fi

if ! gh pr create --title="$title" --body="$body" "$@"; then
    echo "❌ failed to create pr"
fi
